version: '3.8'

services:
  frontend:
    image: lilfizz/frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
    networks:
      - app-network

  backend:
    image: lilfizz/backend:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    ports:
      - "3001:3001"
    deploy:
      replicas: 2
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
